# Generated by Django 5.1.4 on 2026-06-15 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код типа')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип проверки задания',
                'verbose_name_plural': 'Типы проверок заданий',
            },
        ),
        migrations.CreateModel(
            name='EcoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('reward', models.IntegerField(default=10, verbose_name='Награда (ECO)')),
                ('secret_code', models.CharField(blank=True, help_text='Если заполнено, пользователь должен ввести ровно этот код. Сравнение без учета регистра.', max_length=50, verbose_name="Секретный код (если тип 'Ввод текста')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('task_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.ecotasktype', verbose_name='Способ проверки')),
            ],
            options={
                'verbose_name': 'Эко-задание',
                'verbose_name_plural': 'Эко-задания',
            },
        ),
        migrations.CreateModel(
            name='UserTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_text', models.CharField(blank=True, max_length=500, verbose_name='Текстовое доказательство')),
                ('proof_image', models.ImageField(blank=True, upload_to='tasks_proofs/', verbose_name='Фото доказательство')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('ai_approved', 'Одобрено ИИ'), ('ai_rejected', 'Отклонено ИИ (На ручной проверке)'), ('approved', 'Одобрено (Баллы начислены)'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено (Списание)')], default='pending', max_length=20, verbose_name='Статус')),
                ('ai_feedback', models.TextField(blank=True, help_text='Что ответил ИИ при проверке', null=True, verbose_name='Комментарий ИИ')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий админа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.ecotask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'ai_approved', 'ai_rejected', 'approved'])), fields=('user', 'task'), name='unique_active_task_completion')],
            },
        ),
    ]
